#!/bin/bash

alias gc="git clone"
alias gs="git status"
alias ls="ls -alGh"

alias e="emacs -nw"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

alias dotfiles='code ~/code/dotfiles'

if which -s docker; then

	ectags() {
		docker run --rm -it -v $(pwd):/root/ctags-workspace --name ctags larrywright/ctags
	}
	aws(){
		docker run -it --rm \
			-v "${HOME}/.aws:/root/.aws" \
			--log-driver none \
			--name aws \
			jess/awscli "$@"
	}

	http(){
		docker run -it --rm \
			--net host \
			-v "$PWD":/downloads \
			-w /downloads  \
			larrywright/httpie "$@"
	}

	wget(){
		http --download "$@"
	}

	hostess(){
		sudo docker run -it --rm \
			-v /etc/hosts:/etc/hosts \
			larrywright/hostess "$@"
	}

	hugod(){
		docker run -it --rm --name hugo --net host \
			-v "$PWD":/blog larrywright/hugo "$@"
	}

	hugos(){
		docker run -it --rm --name hugo --net host \
			-v "$PWD":/blog larrywright/hugo server -w
	}
fi 