#!/bin/bash

alias gc="git clone"
alias gs="git status"
alias ls="ls -alGh"

alias e="emacs"

alias od="cd ~/Documents/OneDrive"

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"
# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"

# Print each PATH entry on a separate line
alias path='echo -e ${PATH//:/\\n}'

alias templates='code ~/Documents/OneDrive/Reference/Project\ Templates/'

alias dotfiles='code ~/code/dotfiles'

alias plan='cat ~/.plan'

export DOCKER_REPO_PREFIX=jess

ectags() {
	docker run --rm -it -v $(pwd):/root/ctags-workspace --name ctags larrywright/ctags
}
aws(){
	docker run -it --rm \
		-v "${HOME}/.aws:/root/.aws" \
		--log-driver none \
		--name aws \
		${DOCKER_REPO_PREFIX}/awscli "$@"
}

http(){
	docker run -it --rm \
    --net host \
    -v "$PWD":/downloads \
    -w /downloads  \
    larrywright/httpie "$@"
}

wget(){
	http --download "$@"
}

hostess(){
  sudo docker run -it --rm \
    -v /etc/hosts:/etc/hosts \
    larrywright/hostess "$@"
}

hugod(){
	docker run -it --rm --name hugo --net host \
		-v "$PWD":/blog larrywright/hugo "$@"
}

hugos(){
	docker run -it --rm --name hugo --net host \
		-v "$PWD":/blog larrywright/hugo server -w
}