#!/bin/bash

export PATH=/usr/bin:/usr/sbin:/bin:/sbin
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
export PATH=$PATH:/usr/local/opt/python@2/libexec/bin
export EDITOR='code'

export PATH=${PATH}:/usr/local/bin
export PATH="~/bin:$PATH"

# Larger bash history (allow 32³ entries; default is 500)
export HISTSIZE=50000000;
export HISTFILESIZE=$HISTSIZE;
export HISTCONTROL=ignoredups;
# Make some commands not show up in history
export HISTIGNORE=" *:ls:cd:cd -:pwd:exit:date:* --help:* -h";

# Prefer US English and use UTF-8
export LANG="en_US.UTF-8";
export LC_ALL="en_US.UTF-8";

# For Homebrew + Python
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PYTHONPATH=$HOME/code/innersource/lib-python-api:$HOME/code/innersource/lib-python-api/acp_api:$PYTHONPATH